package modelos;
// Generated 14/08/2017 11:10:41 by Hibernate Tools 4.3.1



/**
 * Persona2 generated by hbm2java
 */
public class Persona2  implements java.io.Serializable {


     private Integer usuario;
     private String nombre;
     private String correo;

    public Persona2() {
    }

    public Persona2(String nombre, String correo) {
       this.nombre = nombre;
       this.correo = correo;
    }
   
    public Integer getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Integer usuario) {
        this.usuario = usuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }




}


